---
- name: Login OC
  shell: 
    cmd: "oc login --server={{oc_host}} --username={{oc_username}} --password={{oc_password}} --insecure-skip-tls-verify"
- name: Download artifact
  maven_artifact:
    group_id: "{{ app_group_id }}"
    artifact_id: "{{ app_artifact_id }}"
    repository_url: "{{ maven_repository_url }}"
    extension: "{{ artifact_extension_type }}"
    version: "{{ app_version }}"
    dest: "{{ app_folder }}/{{ app_artifact_id }}-{{ app_version }}.{{ artifact_extension_type }}"
- name: Ensure the Namespace exists
  shell: 
    cmd: "oc get project {{oc_project}}"
  register: ocp_ns
  ignore_errors: yes
- name: print ocp_ns
  debug:
    msg: "{{ocp_ns}}"
- name: If not exists create Namespace
  shell: 
    cmd: "oc new-project {{oc_project}}"
  when: "'Error from server (NotFound)' in ocp_ns.stderr"
- name: Ensure the BuildConfig exists
  shell: 
    cmd: "oc get bc {{ app_artifact_id }} -n {{oc_project}}"
  register: ocp_bc
  ignore_errors: yes
- name: If not exists create BC
  shell: 
    cmd: "oc new-build java --name {{ app_artifact_id }} --binary -n {{oc_project}}"
  when: "'Error from server (NotFound)' in ocp_bc.stderr"
- name: Upload jar to image
  shell: 
    cmd: "oc start-build {{ app_artifact_id }} --from-file={{ app_folder }}/{{ app_artifact_id }}-{{ app_version }}.{{ artifact_extension_type }} --follow -n {{oc_project}}"
- name: Ensure the BuildConfig exists
  shell: 
    cmd: "oc get deployment {{ app_artifact_id }} -n {{oc_project}}"
  register: ocp_dc
  ignore_errors: yes
- name: Create POD
  shell: 
    cmd: "oc new-app {{ app_artifact_id }} -n {{oc_project}}"
  when: "'Error from server (NotFound)' in ocp_dc.stderr"
- name: Modify quarkus rest  port with ClusterIP
  shell: 
    cmd: "oc patch svc/{{ app_artifact_id }} -p '{\"spec\":{\"ports\":[{\"name\":\"8080-tcp\",\"port\":8080,\"targetPort\":9080,\"protocol\":\"TCP\"}]}}' -n {{oc_project}}"
- name: Ensure the Route exists
  shell: 
    cmd: "oc get routes {{ app_artifact_id }} -n {{oc_project}}"
  register: ocp_route
  ignore_errors: yes
- name: Create Route
  shell: 
    cmd: "oc expose svc {{ app_artifact_id }} -n {{oc_project}}"
  when: "'Error from server (NotFound)' in ocp_route.stderr"